language: node_js
node_js:
  - "node"
  - "6.1"
  - "5.10"
  - "4.4"
  - "0.12"
addons:
    code_climate:
        repo_token: 79816a32349b15a909e262a88676bf1d51021ad6848b96706411bb2b829dd5b6
after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
